name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Lint and Code Quality
      run: ./gradlew lint

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Run UI Tests
      run: ./gradlew connectedAndroidTest

    - name: Package APK or Bundle
      run: ./gradlew bundleRelease

    - name: Upload html test report
      uses: actions/upload-artifact@v3
      with:
        name: index.html
        path: app/build.reports/lint-results-debug.html